set_profile:
  description: "Configure the profile for auto-mode."
  target:
    device:
      integration: "zcsmower"
    entity:
      domain: device_tracker
  fields:
    profile:
      name: "Profile"
      description: "Select the profile you want to use."
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"

work_until:
  description: "Command the lawn mower to mow until a certain time."
  target:
    device:
      integration: "zcsmower"
    entity:
      domain: device_tracker
  fields:
    area:
      name: "Zone"
      description: "Zone where the lawn mower should start."
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    hours:
      name: "Hours"
      description: "Time until which lawn mower should drive in locale time and 24h format."
      example: "12"
      default: 1
      selector:
        number:
          min: 1
          max: 24
          step: 1
          mode: slider
    minutes:
      name: "Minutes"
      description: "Time until which lawn mower should drive in locale time and 24h format."
      example: "30"
      default: 1
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

border_cut:
  description: "Command the lawn mower to cut the border."
  target:
    device:
      integration: "zcsmower"
    entity:
      domain: device_tracker

charge_until:
  description: "Command the lawn mower to charge until a certain time."
  target:
    device:
      integration: "zcsmower"
    entity:
      domain: device_tracker
  fields:
    hours:
      name: "Hours"
      description: "Time until which lawn mower should charge in locale time and 24h format."
      example: "12"
      default: 1
      selector:
        number:
          min: 1
          max: 24
          step: 1
          mode: slider
    minutes:
      name: "Minutes"
      description: "Time until which lawn mower should charge in locale time and 24h format."
      example: "30"
      default: 1
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider
    weekday:
      name: "Day of week"
      description: "Numeric representation of the day of the week is 0 (for Sunday) through 6 (for Saturday)."
      example: "1"
      default: 0
      selector:
        number:
          min: 0
          max: 6
          step: 1
          mode: slider
