set_profile:
  description: "Configure the profile for auto-mode."
  fields:
    imei:
      description: "IMEI of the lawn mower"
      example: "350000000000000"
      required: True
      selector:
        text:
    profile:
      description: "Profile"
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"

work_until:
  description: "Command the lawn mower to mow until a certain time."
  fields:
    imei:
      description: "IMEI of the lawn mower"
      example: "350000000000000"
      required: True
      selector:
        text:
    area:
      description: "Zone where the lawn mower should start."
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    hours:
      description: "Time until which lawn mower should drive in locale time and 24h format."
      example: "12"
      default: 1
      selector:
        number:
          min: 1
          max: 24
          step: 1
          mode: slider
    minutes:
      description: "Time until which lawn mower should drive in locale time and 24h format."
      example: "30"
      default: 1
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

border_cut:
  description: "Command the lawn mower to cut the border."
  fields:
    imei:
      description: "IMEI of the lawn mower"
      example: "350000000000000"
      required: True
      selector:
        text:

charge_until:
  description: "Command the lawn mower to charge until a certain time."
  fields:
    imei:
      description: "IMEI of the lawn mower"
      example: "350000000000000"
      required: True
      selector:
        text:
    hours:
      description: "Time until which lawn mower should charge in locale time and 24h format."
      example: "12"
      default: 1
      selector:
        number:
          min: 1
          max: 24
          step: 1
          mode: slider
    minutes:
      description: "Time until which lawn mower should charge in locale time and 24h format."
      example: "30"
      default: 1
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider
    hours:
      description: "Numeric representation of the day of the week is 0 (for Sunday) through 6 (for Saturday)."
      example: "1"
      default: 0
      selector:
        number:
          min: 0
          max: 6
          step: 1
          mode: slider
